### ISSUE TITLE
Cannot get the list of all datasets for a feed in one API call

### ISSUE THREAD

**Issue by jcpitre** [MobilityData/mobility-feed-api#462] opened 2024-06-07 13:51 UTC
### Describe the bug

Using the `v1/gtfs_feeds/{id}/datasets` endpoint, we cannot obtain the list of all datasets for a given feed. It's either the latest, or not the latest (depending on the latest parameter). If latest is not specified, it seems to default to false.

### Steps/Code to Reproduce

A call to `v1/gtfs_feeds/mdb-279/datasets?latest=true` returned `mdb-279-202403190153`
A call to `v1/gtfs_feeds/mdb-279/datasets?latest=false` returned `mdb-279-202402071826`.
A call to `v1/gtfs_feeds/mdb-279/datasets` returned `mdb-279-202402071826`, i.e. the same as when `latest` is `false`.

You can test this with any feed that has more than one dataset

### Expected Results

`v1/gtfs_feeds/mdb-279/datasets` (i.e. latest not specified) should return all the datasets, latest or not.

### Actual Results

See above

**Comment by cka-y** [comment] 2024-07-02 20:27
I was unable to reproduce this bug with the current state of the API. Here are the details of my findings using the dev API:

According to the Open API specification, the `latest` parameter is defined as:
> Boolean - If true, only return the latest dataset.

From my understanding, this means that if `latest` is `false`, all datasets should be returned.

### Test Cases:

1. **Running without the `latest` parameter specified:**
   According to the specification, this should default to `false`, i.e., display all datasets, which seems to be the case.

   - **Query:**
     ```bash
     curl --location 'https://api-dev.mobilitydatabase.org/v1/gtfs_feeds/mdb-279/datasets' --header 'Accept: application/json' --header 'Authorization: Bearer [Token]'
     ```
   - **Response:**
     Both `mdb-279-202407021354` and `mdb-279-202406182025` are returned.

     <details><summary>See full response</summary>

     ```json
      [
       {
         "id": "mdb-279-202406182025",
         "feed_id": "mdb-279",
         "hosted_url": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202406182025/mdb-279-202406182025.zip",
         "note": null,
         "downloaded_at": "2024-06-18T20:00:26.234781+00:00",
         "hash": "25f1f4d2d2a5b0af81f0d6fd805d2161d9480e0a38e816887d35fe1d1593183a",
         "bounding_box": {
           "minimum_latitude": 47.623688,
           "maximum_latitude": 48.370108,
           "minimum_longitude": -124.636859,
           "maximum_longitude": -122.511536
         },
         "validation_report": {
           "validated_at": "2024-06-27T13:13:08+00:00",
           "features": [
             "Transfers",
             "Fares V1",
             "Shapes",
             "Feed Information",
             "Route Colors",
             "Headsigns",
             "Wheelchair Accessibility",
             "Bikes Allowance",
             "Continuous Stops"
           ],
           "validator_version": "5.0.2-SNAPSHOT",
           "total_error": 0,
           "total_warning": 20,
           "total_info": 0,
           "unique_error_count": 0,
           "unique_warning_count": 1,
           "unique_info_count": 0,
           "url_json": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202406182025/report_5.0.2-SNAPSHOT.json",
           "url_html": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202406182025/report_5.0.2-SNAPSHOT.html"
         }
       },
       {
         "id": "mdb-279-202407021354",
         "feed_id": "mdb-279",
         "hosted_url": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/mdb-279-202407021354.zip",
         "note": null,
         "downloaded_at": "2024-07-02T13:40:55.660800+00:00",
         "hash": "954bbf7239c7968054e07bb3a77cc7ea32111ee044960a4a49f7813046cb1162",
         "bounding_box": {
           "minimum_latitude": 47.623688,
           "maximum_latitude": 48.370108,
           "minimum_longitude": -124.636859,
           "maximum_longitude": -122.511536
         },
         "validation_report": {
           "validated_at": "2024-07-02T13:41:55+00:00",
           "features": [
             "Transfers",
             "Fares V1",
             "Shapes",
             "Feed Information",
             "Route Colors",
             "Headsigns",
             "Wheelchair Accessibility",
             "Bikes Allowance",
             "Continuous Stops"
           ],
           "validator_version": "5.0.2-SNAPSHOT",
           "total_error": 0,
           "total_warning": 20,
           "total_info": 0,
           "unique_error_count": 0,
           "unique_warning_count": 1,
           "unique_info_count": 0,
           "url_json": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/report_5.0.2-SNAPSHOT.json",
           "url_html": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/report_5.0.2-SNAPSHOT.html"
         }
       }
     ]
     ``` 
     </details>


2. **Running with `?latest=false`:**
   Returns the same result as without the `latest` parameter.
   - **Query:**
     ```bash
     curl --location 'https://api-dev.mobilitydatabase.org/v1/gtfs_feeds/mdb-279/datasets?latest=false' --header 'Accept: application/json' --header 'Authorization: Bearer [Token]'
     ```
   - **Response:**
     Both `mdb-279-202407021354` and `mdb-279-202406182025` are returned.

 
     <details><summary>See full response</summary>

     ```json
      [
       {
         "id": "mdb-279-202406182025",
         "feed_id": "mdb-279",
         "hosted_url": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202406182025/mdb-279-202406182025.zip",
         "note": null,
         "downloaded_at": "2024-06-18T20:00:26.234781+00:00",
         "hash": "25f1f4d2d2a5b0af81f0d6fd805d2161d9480e0a38e816887d35fe1d1593183a",
         "bounding_box": {
           "minimum_latitude": 47.623688,
           "maximum_latitude": 48.370108,
           "minimum_longitude": -124.636859,
           "maximum_longitude": -122.511536
         },
         "validation_report": {
           "validated_at": "2024-06-27T13:13:08+00:00",
           "features": [
             "Transfers",
             "Fares V1",
             "Shapes",
             "Feed Information",
             "Route Colors",
             "Headsigns",
             "Wheelchair Accessibility",
             "Bikes Allowance",
             "Continuous Stops"
           ],
           "validator_version": "5.0.2-SNAPSHOT",
           "total_error": 0,
           "total_warning": 20,
           "total_info": 0,
           "unique_error_count": 0,
           "unique_warning_count": 1,
           "unique_info_count": 0,
           "url_json": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202406182025/report_5.0.2-SNAPSHOT.json",
           "url_html": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202406182025/report_5.0.2-SNAPSHOT.html"
         }
       },
       {
         "id": "mdb-279-202407021354",
         "feed_id": "mdb-279",
         "hosted_url": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/mdb-279-202407021354.zip",
         "note": null,
         "downloaded_at": "2024-07-02T13:40:55.660800+00:00",
         "hash": "954bbf7239c7968054e07bb3a77cc7ea32111ee044960a4a49f7813046cb1162",
         "bounding_box": {
           "minimum_latitude": 47.623688,
           "maximum_latitude": 48.370108,
           "minimum_longitude": -124.636859,
           "maximum_longitude": -122.511536
         },
         "validation_report": {
           "validated_at": "2024-07-02T13:41:55+00:00",
           "features": [
             "Transfers",
             "Fares V1",
             "Shapes",
             "Feed Information",
             "Route Colors",
             "Headsigns",
             "Wheelchair Accessibility",
             "Bikes Allowance",
             "Continuous Stops"
           ],
           "validator_version": "5.0.2-SNAPSHOT",
           "total_error": 0,
           "total_warning": 20,
           "total_info": 0,
           "unique_error_count": 0,
           "unique_warning_count": 1,
           "unique_info_count": 0,
           "url_json": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/report_5.0.2-SNAPSHOT.json",
           "url_html": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/report_5.0.2-SNAPSHOT.html"
         }
       }
     ]
     ``` 
     </details>


3. **Running with `?latest=true`:**
   Returns only the latest dataset.
   - **Query:**
     ```bash
     curl --location 'https://api-dev.mobilitydatabase.org/v1/gtfs_feeds/mdb-279/datasets?latest=true' --header 'Accept: application/json' --header 'Authorization: Bearer [Token]'
     ```
   - **Response:**
     Only `mdb-279-202407021354` is returned, which is the latest dataset.
     <details><summary>See full response</summary>


     ```json
     [
       {
         "id": "mdb-279-202407021354",
         "feed_id": "mdb-279",
         "hosted_url": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/mdb-279-202407021354.zip",
         "note": null,
         "downloaded_at": "2024-07-02T13:40:55.660800+00:00",
         "hash": "954bbf7239c7968054e07bb3a77cc7ea32111ee044960a4a49f7813046cb1162",
         "bounding_box": {
           "minimum_latitude": 47.623688,
           "maximum_latitude": 48.370108,
           "minimum_longitude": -124.636859,
           "maximum_longitude": -122.511536
         },
         "validation_report": {
           "validated_at": "2024-07-02T13:41:55+00:00",
           "features": [
             "Transfers",
             "Fares V1",
             "Shapes",
             "Feed Information",
             "Route Colors",
             "Headsigns",
             "Wheelchair Accessibility",
             "Bikes Allowance",
             "Continuous Stops"
           ],
           "validator_version": "5.0.2-SNAPSHOT",
           "total_error": 0,
           "total_warning": 20,
           "total_info": 0,
           "unique_error_count": 0,
           "unique_warning_count": 1,
           "unique_info_count": 0,
           "url_json": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/report_5.0.2-SNAPSHOT.json",
           "url_html": "https://dev-files.mobilitydatabase.org/mdb-279/mdb-279-202407021354/report_5.0.2-SNAPSHOT.html"
         }
       }
     ]
     ```
     </details>

**Comment by cka-y** [comment] 2024-07-03 16:16
After testing by pointing the local API to the PROD database, I can confirm that the behavior remains the same. The latest dataset for feed `mdb-279`, which is `mdb-279-202405270023`, is returned regardless of whether `?latest=true`, `?latest=false`, or no `latest` filtering parameter is specified.

**Comment by cka-y** [comment] 2024-07-03 16:19
Closing as this bug is irreproducible.

**Closed by cka-y** 2024-07-03 16:19 UTC
Labels: bug
