### ISSUE TITLE
Add privacy policy consent to the registration process

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#107] opened 2023-09-20 19:56 UTC
### Describe the problem

As part of the registration process, the user needs to consent to the MobilityData privacy policy to be able to create an account and use the API/UI. If the privacy policy is not consented, the account cannot be created.

### Proposed solution

Add a consent checkbox and the link to MobilityData's privacy policy as part of the registration process. The consent can be added as part of the UI added by #99.

**Comment by davidgamez** [comment] 2023-09-20 20:53
👁️ @fredericsimard

**Comment by fredericsimard** [comment] 2023-09-20 20:56
I believe that linking to the Privacy policy on the main website should do, no need to store a separate copy on this server.

**Comment by fredericsimard** [comment] 2023-09-20 20:58
Also we need to document that approval as much as possible, when, IP address (if possible) or Country, Province/State should be enough, etc.

**Comment by emmambd** [comment] 2024-01-23 20:33
Duplicate of #109

**Closed by emmambd** 2024-01-23 20:33 UTC
Labels: enhancement
